import type { AiUseCase, Assessment } from "./types";

/**
 * Example register entries, to show how the register works. Every one is flagged `example`, named "Example: …" and
 * described as example data, so it can't be mistaken for a real use case in the app, the exports or the PDF.
 * Owners use example.com addresses (reserved for examples, RFC 2606).
 */
export function exampleEntries(assessment: Pick<Assessment, "jewels">): AiUseCase[] {
  const microsoft = assessment.jewels.filter((j) => j.platform === "microsoft").slice(0, 2).map((j) => j.id);
  const first = assessment.jewels.slice(0, 1).map((j) => j.id);
  return [
    {
      id: "example-copilot",
      example: true,
      kind: "m365-copilot",
      name: "Example: Microsoft 365 Copilot for all staff",
      reference: "EX-AI-001",
      description: "EXAMPLE DATA. Copilot in the Microsoft 365 apps for drafting, summarising and finding internal documents. Business objective: save staff time on routine writing and searching.",
      product: "Microsoft 365 Copilot",
      technology: ["generative-ai", "natural-language-processing"],
      lifecycle: "operate",
      technicalStandard: "partially-applied",
      domains: ["corporate"],
      usagePatterns: ["workplace-productivity"],
      ownerName: "Jo Example",
      ownerEmail: "jo.example@example.com",
      criteria: ["c4"],
      inherentRisk: "medium",
      residualRisk: "low",
      impactAssessmentDate: "2026-07-01",
      autonomy: "assists",
      access: "delegated",
      data: ["official", "personal"],
      jewels: microsoft,
      answers: {
        "AIR-ACC-001": "yes",
        "AIR-ACC-002": "partial",
        "AIR-OVR-001": "yes",
        "AIR-ACS-002": "partial",
        "AIR-DAT-001": "yes",
        "AIR-DAT-005": "no",
        "AIR-MON-001": "partial",
        "AIR-OFF-002": "yes",
        "AIR-OFF-003": "unknown",
        "AIR-TRN-001": "yes",
        "AIR-TRN-002": "no",
        "AIR-ASR-001": "yes",
      },
      notes: { "AIR-DAT-005": "Example note: records team to confirm which Copilot chats are records." },
    },
    {
      id: "example-triage-agent",
      example: true,
      kind: "in-house-agent",
      name: "Example: Grant application triage agent",
      reference: "EX-AI-002",
      description:
        "EXAMPLE DATA. An agent that reads incoming grant applications, checks them against the eligibility rules, drafts a recommendation and routes it to an assessor, who decides. Business objective: faster, more consistent triage.",
      product: "",
      technology: ["generative-ai", "natural-language-processing"],
      lifecycle: "discover",
      technicalStandard: "partially-applied",
      domains: ["service-delivery"],
      usagePatterns: ["decision-making"],
      ownerName: "Sam Example",
      ownerEmail: "sam.example@example.com",
      criteria: ["c1", "c2", "c4"],
      inherentRisk: "high",
      residualRisk: "medium",
      impactAssessmentDate: "2026-08-14",
      lastReview: "2026-08-14",
      nextReview: "2027-08-14",
      autonomy: "hitl",
      access: "scoped",
      data: ["personal", "sensitive", "indigenous"],
      jewels: first,
      answers: {
        "AIR-ACC-001": "yes",
        "AIR-ACC-002": "yes",
        "AIR-ACC-003": "partial",
        "AIR-OVR-001": "yes",
        "AIR-OVR-002": "yes",
        "AIR-OVR-003": "no",
        "AIR-ACS-001": "no",
        "AIR-ACS-002": "partial",
        "AIR-DAT-001": "yes",
        "AIR-DAT-002": "partial",
        "AIR-DAT-003": "unknown",
        "AIR-DAT-004": "partial",
        "AIR-DAT-005": "no",
        "AIR-MON-001": "partial",
        "AIR-MON-002": "no",
        "AIR-OFF-001": "no",
        "AIR-OFF-002": "yes",
        "AIR-OFF-003": "no",
        "AIR-TRN-001": "yes",
        "AIR-TRN-002": "partial",
        "AIR-ASR-001": "yes",
        "AIR-ASR-002": "partial",
        "AIR-ASR-003": "unknown",
      },
      notes: { "AIR-ACS-001": "Example note: the pilot runs under a shared service account; a dedicated identity is planned." },
    },
    {
      id: "example-note-taker",
      example: true,
      kind: "ai-connector",
      name: "Example: Third-party meeting note-taker",
      reference: "EX-AI-003",
      description: "EXAMPLE DATA. A note-taking app connected through OAuth that joins online meetings, records them and emails summaries to attendees.",
      product: "",
      technology: ["generative-ai", "natural-language-processing"],
      lifecycle: "operate",
      technicalStandard: "not-applied",
      domains: ["corporate"],
      usagePatterns: ["workplace-productivity"],
      ownerName: "",
      ownerEmail: "",
      criteria: [],
      autonomy: "hotl",
      access: "org-wide",
      data: ["official", "personal"],
      jewels: [],
      answers: { "AIR-ACC-001": "no", "AIR-ACS-002": "no", "AIR-MON-002": "unknown" },
      notes: {},
    },
  ];
}
