/**
 * Writes the tiny `SOURCES_LAST_CHECKED` constant from `watch/state.json` so the client bundle never ships the whole
 * baseline. Uses the newest feed cursor date in the state file, then the git date of that file.
 */
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const OUT_PATH = join("src", "content", "sourcesChecked.ts");

function fromState(): string | undefined {
  const path = join(root, "watch", "state.json");
  if (!existsSync(path)) return undefined;
  const state = JSON.parse(readFileSync(path, "utf8")) as { feeds?: Record<string, { latest?: string }> };
  const feedDates = Object.values(state.feeds ?? {})
    .map((f) => f.latest?.slice(0, 10))
    .filter((d): d is string => !!d && /^\d{4}-\d{2}-\d{2}$/.test(d))
    .sort()
    .reverse();
  return feedDates[0];
}

function fromGit(): string | undefined {
  try {
    const d = execSync("git log -1 --format=%cs -- watch/state.json", { cwd: root, encoding: "utf8" }).trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(d) ? d : undefined;
  } catch {
    return undefined;
  }
}

export function sourcesLastChecked(): string {
  return fromState() ?? fromGit() ?? "unknown";
}

export function sourcesCheckedText(date = sourcesLastChecked()): string {
  return `/** YYYY-MM-DD the committed source-watch baseline was last updated. Generated by scripts/gen-sources-checked.ts — do not edit. */\nexport const SOURCES_LAST_CHECKED: string = ${JSON.stringify(date)};\n`;
}

export function writeSourcesChecked(): string {
  const text = sourcesCheckedText();
  mkdirSync(join(root, "src", "content"), { recursive: true });
  writeFileSync(join(root, OUT_PATH), text);
  return text;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeSourcesChecked();
  console.log(`wrote ${OUT_PATH} (${sourcesLastChecked()})`);
}
